detection_limits:
  ztfg: 22.0
  ztfr: 22.0
  ztfi: 22.0

data_fillers:
  ztfg: 22.0
  ztfr: 22.0
  ztfi: 22.0
  
dir_path_var: /home/malina.desai/nmma/data/ztf_test/
inj_file_var: injection_test_var.json
label_var: test_var

dir_path_fix: /home/malina.desai/nmma/data/ztf_test/
inj_file_fix: injection_test_fix.json
label_fix: test_fix

step: 0.5
num_repeats: 1
params: ['log10_mej', 'log10_vej', 'log10_Xlan', 'luminosity_distance', 'timeshift']
